'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Badge, Card, CandleLoader, buttonClasses, cn } from '@tradew/ui';
import { fetchResearchAnalysis } from '@/lib/research/api';
import type { PeriodType, ResearchAnalysis, ResearchSection } from '@/lib/research/types';
import { asOf, asOfDate } from '@/lib/research/format';
import { DataUnavailable } from './DataUnavailable';

/**
 * AI research synthesis — grounded, and visibly so.
 *
 * ── WHAT THIS REPLACES ─────────────────────────────────────────────────────
 *
 * A card headed "🤖 TradeW AI Summary · Generated by TradeW AI" showing
 * "Overall Outlook Bullish · Confidence 87% · Business Quality 9.2/10 ·
 * Financial Health 8.8/10 · Risk Medium". None of it came from a model. None of
 * it came from data. It was identical for every symbol.
 *
 * ── WHAT MAKES THIS DIFFERENT, VISIBLY ─────────────────────────────────────
 *
 * 1. It is not generated until the reader asks. A summary that appears on load
 *    reads as a property of the company; one produced on request reads as what
 *    it is — a model's paragraph about the table above it.
 * 2. The EVIDENCE the model was given is rendered underneath, expandable. If a
 *    figure is not in that list, the model did not have it.
 * 3. There is no score, no rating and no outlook verdict anywhere in this
 *    component, because the API has no field for one.
 *
 * When the account lacks `ai_research`, this is the ONLY thing on the page that
 * changes — every statement, ratio and chart stays fully readable, which is the
 * entitlement boundary the product intends.
 */
export function AiResearchPanel({ symbol, periodType }: { symbol: string; periodType: PeriodType }) {
  const [state, setState] = useState<
    | { status: 'idle' }
    | { status: 'loading' }
    | { status: 'done'; section: ResearchSection<ResearchAnalysis> & { entitlementRequired?: boolean } }
    | { status: 'error'; message: string }
  >({ status: 'idle' });
  const [showEvidence, setShowEvidence] = useState(false);

  const run = async () => {
    setState({ status: 'loading' });
    try {
      const section = await fetchResearchAnalysis(symbol, periodType);
      setState({ status: 'done', section });
    } catch (err) {
      setState({
        status: 'error',
        message: err instanceof Error ? err.message : 'The analysis request could not be completed.',
      });
    }
  };

  return (
    <Card
      title="AI research"
      subtitle="· a summary of the data above, not a rating"
      actions={
        state.status !== 'loading' && (
          <button type="button" onClick={run} className={buttonClasses({ variant: 'outline', size: 'sm' })}>
            {state.status === 'idle' ? 'Generate summary' : 'Regenerate'}
          </button>
        )
      }
    >
      {state.status === 'idle' && (
        <p className="max-w-2xl text-xs leading-relaxed text-muted">
          TradeW can summarise the statements, ratios and reconciliation shown on this page. The summary is built only
          from those figures — it introduces no metric of its own, and it produces no score, rating, price target or
          recommendation. Every figure it is given is listed alongside the result.
        </p>
      )}

      {state.status === 'loading' && (
        <div className="flex flex-col items-center gap-2 py-8">
          <CandleLoader size="sm" label="Reading the statements" />
          <p className="text-[11px] text-faint">Summarising the retrieved financial data…</p>
        </div>
      )}

      {state.status === 'error' && (
        <DataUnavailable
          title="Analysis could not be generated"
          reason={state.message}
          action={
            <button type="button" onClick={run} className={buttonClasses({ variant: 'outline', size: 'sm' })}>
              Try again
            </button>
          }
        />
      )}

      {state.status === 'done' && !state.section.available && (
        <DataUnavailable
          title={state.section.entitlementRequired ? 'AI research is a premium feature' : 'Analysis unavailable'}
          reason={state.section.reason}
          action={
            state.section.entitlementRequired ? (
              <Link href="/settings/subscription" className={buttonClasses({ variant: 'primary', size: 'sm' })}>
                See plans
              </Link>
            ) : undefined
          }
        />
      )}

      {state.status === 'done' && state.section.available && (
        <AnalysisBody analysis={state.section.data} onToggleEvidence={() => setShowEvidence((v) => !v)} showEvidence={showEvidence} />
      )}
    </Card>
  );
}

function AnalysisBody({
  analysis,
  showEvidence,
  onToggleEvidence,
}: {
  analysis: ResearchAnalysis;
  showEvidence: boolean;
  onToggleEvidence: () => void;
}) {
  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-2">
        <Badge tone="neutral" className="px-1.5 py-0 text-[9px]">
          {analysis.provider} · {analysis.model}
        </Badge>
        <span className="text-[10.5px] text-faint">generated {asOf(analysis.generatedAt)}</span>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        {analysis.sections.map((s) => (
          <section key={s.heading} className="rounded-lg border border-border px-3 py-2.5">
            <h3 className="text-[11px] font-bold uppercase tracking-wide text-teal">{s.heading}</h3>
            <p className="mt-1 text-[11.5px] leading-relaxed text-muted">{s.body}</p>
          </section>
        ))}
      </div>

      <div className="rounded-lg border border-border2 bg-bg/40 px-3 py-2">
        <button
          type="button"
          onClick={onToggleEvidence}
          aria-expanded={showEvidence}
          className="flex w-full items-center gap-1.5 text-left text-[11px] font-bold text-muted transition-colors hover:text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus"
        >
          <span aria-hidden="true" className={cn('transition-transform', !showEvidence && '-rotate-90')}>
            ▾
          </span>
          Analysis based on {analysis.evidence.length} verified input
          {analysis.evidence.length === 1 ? '' : 's'}
        </button>

        {showEvidence && (
          <ul className="mt-2 space-y-1">
            {analysis.evidence.map((e, i) => (
              <li key={`${e.label}-${i}`} className="text-[10.5px] leading-relaxed text-faint">
                <span className="font-semibold text-muted">{e.label}</span> — {e.detail}
                {/* A date, not the raw ISO stamp the API carries. */}
                {e.sourceTimestamp && <span className="text-faint"> (period ending {asOfDate(e.sourceTimestamp)})</span>}
              </li>
            ))}
          </ul>
        )}
      </div>

      <p className="text-[10.5px] leading-relaxed text-faint">{analysis.disclaimer}</p>
    </div>
  );
}
