/**
 * The normalized fundamental-research domain.
 *
 * ── THE ONE RULE ───────────────────────────────────────────────────────────
 *
 * Every type in this file is shaped so that "we do not have this number" is
 * REPRESENTABLE and "we have a made-up number" is NOT. Concretely:
 *
 *   · A missing metric is an ABSENT key, never `0` and never `null` masquerading
 *     as a value. Consumers must branch on presence.
 *   · Every present value carries its own provenance — where it came from, when
 *     the vendor stamped it, when we fetched it, and whether the vendor reported
 *     it or we derived it.
 *   · A whole section that could not be retrieved is a discriminated union with
 *     no data field at all (`FundamentalsSection`), so there is nowhere for a
 *     placeholder to live.
 *
 * This exists because the surface it feeds — `/research` — previously rendered
 * hardcoded P/E, ROE, EPS and shareholding figures identically for every symbol,
 * plus an "AI summary" generated by nothing. The fix is not vigilance; it is a
 * type system in which the old page could not have compiled.
 *
 * ── WHY THIS LIVES IN packages/market-data ─────────────────────────────────
 *
 * Same reason the Dhan, Binance and Twelve Data clients do: it is a provider
 * contract plus pure normalization, consumed by a runtime (`services/api`)
 * rather than being one. ARCHITECTURE.md §6 — shared libraries in `packages/`,
 * runtimes in `services/`.
 */

/** Which statement a fact belongs to. */
export type StatementType = 'income' | 'balance' | 'cash_flow';

/** Reporting cadence. Vendors expose both; not every issuer files both. */
export type PeriodType = 'annual' | 'quarterly';

/**
 * Did the vendor report this number, or did we compute it?
 *
 * Load-bearing, not decorative: "Free Cash Flow = Operating Cash Flow − CapEx"
 * is a defensible derivation, but a reader comparing our FCF against an annual
 * report needs to know it was not lifted from one. The UI labels derived rows.
 */
export type ValueBasis = 'reported' | 'derived';

/** Where a number came from and when — attached to every single value. */
export interface Provenance {
  /** Vendor/system id, e.g. 'twelvedata'. Never a human-facing label. */
  source: string;
  /**
   * The vendor's own timestamp for the datum (filing date, statement period end,
   * quote time). Null when the vendor publishes none — which is itself
   * information, and is shown as "vendor published no timestamp" rather than
   * being backfilled with `fetchedAt`.
   */
  sourceTimestamp: string | null;
  /** When THIS system retrieved it. Always known. */
  fetchedAt: string;
}

/**
 * One financial-statement line item for one period.
 *
 * `value` is a plain number in `currency` units (not paise/cents) — statement
 * magnitudes exceed nothing JS floats cannot hold at the precision vendors
 * publish, and rendering rounds anyway. The DB column is a Decimal; this is the
 * transport shape.
 */
export interface FinancialFact {
  metric: string;
  value: number;
  currency: string;
  basis: ValueBasis;
  provenance: Provenance;
}

/** One reporting period's worth of facts for one statement. */
export interface StatementPeriod {
  /** Fiscal year the period belongs to, per the vendor. */
  fiscalYear: number;
  /** 1-4 for quarterly periods; absent for annual. */
  fiscalQuarter?: number;
  /** ISO date of period end. The label the UI sorts and captions by. */
  periodEnd: string;
  periodType: PeriodType;
  currency: string;
  /**
   * Metric -> fact. ABSENT KEY means the vendor did not publish that line for
   * this period. There is deliberately no "0 means missing" convention.
   */
  facts: Record<string, FinancialFact>;
}

/** A complete statement across periods, newest first. */
export interface FinancialStatement {
  statementType: StatementType;
  periodType: PeriodType;
  symbol: string;
  periods: StatementPeriod[];
}

/**
 * Company identity and the slow-moving descriptive fields.
 *
 * Everything optional except symbol/exchange, because vendors' coverage of
 * sector/industry/employees is genuinely patchy outside large caps, and an
 * absent industry must render as absent rather than as "—" pretending to be a
 * value the company does not have.
 */
export interface CompanyProfile {
  symbol: string;
  exchange: string;
  name: string;
  currency: string;
  sector?: string;
  industry?: string;
  country?: string;
  isin?: string;
  website?: string;
  employees?: number;
  description?: string;
  provenance: Provenance;
}

/**
 * Point-in-time market statistics.
 *
 * Deliberately NOT merged into `CompanyProfile`: these move every session and
 * the profile does not, so they carry a separate provenance stamp and the UI
 * can show two different "as of" times honestly instead of one averaged lie.
 */
export interface CompanyStatistics {
  symbol: string;
  currency: string;
  marketCap?: number;
  enterpriseValue?: number;
  sharesOutstanding?: number;
  floatShares?: number;
  fiftyTwoWeekHigh?: number;
  fiftyTwoWeekLow?: number;
  beta?: number;
  dividendYield?: number;
  /**
   * Vendor-published trailing/forward P/E. Kept separate from the ratios we
   * compute ourselves (`ratios.ts`) so the UI can show ours, the vendor's, or
   * both, and never silently present one as the other. Forward P/E is passed
   * through ONLY when the vendor publishes it — this system has no earnings
   * estimates of its own and will not invent a forward number.
   */
  vendorTrailingPe?: number;
  vendorForwardPe?: number;
  vendorPegRatio?: number;
  provenance: Provenance;
}

/** A single holder or holder-category slice of the register. */
export interface OwnershipSlice {
  /** e.g. 'Promoters', 'Institutions', 'Insiders', or a named holder. */
  holder: string;
  /** Percentage of shares outstanding, 0-100. */
  percent: number;
  /** Share count where the vendor publishes one. */
  shares?: number;
}

export interface OwnershipBreakdown {
  symbol: string;
  /** ISO date the register was measured. Never inferred from fetch time. */
  asOf: string | null;
  categories: OwnershipSlice[];
  topHolders: OwnershipSlice[];
  provenance: Provenance;
}

/** Revenue/operating income split by business line or geography. */
export interface SegmentBreakdown {
  symbol: string;
  dimension: 'business' | 'geography';
  periodEnd: string;
  currency: string;
  rows: Array<{
    name: string;
    revenue?: number;
    operatingIncome?: number;
  }>;
  provenance: Provenance;
}

/** A symbol-search hit. Exchange-aware, because 'INFY' exists on NSE and NYSE. */
export interface SymbolSearchHit {
  symbol: string;
  name: string;
  exchange: string;
  micCode?: string;
  country?: string;
  currency?: string;
  instrumentType?: string;
}

/**
 * The typed failure for this whole subsystem.
 *
 * Mirrors `FxDataUnavailableError` and `DhanFault`: a named error the calling
 * service maps to a 503-with-reason, so the UI can say WHY nothing is shown.
 * `detail` is safe to surface to users — it must never carry the API key, and
 * the provider is responsible for keeping it that way.
 */
export class FundamentalsUnavailableError extends Error {
  readonly detail: string;
  constructor(detail: string) {
    super(`Fundamental data is unavailable (${detail})`);
    this.name = 'FundamentalsUnavailableError';
    this.detail = detail;
  }
}

/**
 * The provider port.
 *
 * Every method either RESOLVES with real vendor data or THROWS
 * `FundamentalsUnavailableError`. There is no third outcome — in particular no
 * "empty but successful" result that a caller could mistake for "this company
 * has no revenue". A vendor that genuinely returns an empty statement list is
 * an unavailability, and providers must raise it as one.
 */
export interface FinancialDataProvider {
  readonly name: string;
  searchSymbols(query: string, limit: number): Promise<SymbolSearchHit[]>;
  getProfile(symbol: string): Promise<CompanyProfile>;
  getStatistics(symbol: string): Promise<CompanyStatistics>;
  getStatement(symbol: string, type: StatementType, periodType: PeriodType): Promise<FinancialStatement>;
  /** Optional coverage — providers that do not publish it throw. */
  getOwnership(symbol: string): Promise<OwnershipBreakdown>;
  /** Optional coverage — providers that do not publish it throw. */
  getSegments(symbol: string): Promise<SegmentBreakdown[]>;
  healthCheck(): Promise<boolean>;
}

// ───────────────────────── canonical metric keys ─────────────────────────────
//
// One vocabulary, so the cache, the ratio engine, the reconciliation check and
// the UI all name the same line the same way regardless of which vendor is
// behind the provider port. Vendor field names are mapped INTO these; nothing
// downstream ever sees a vendor's spelling.

export const INCOME_METRICS = {
  revenue: 'revenue',
  costOfRevenue: 'cost_of_revenue',
  grossProfit: 'gross_profit',
  operatingExpenses: 'operating_expenses',
  sellingGeneralAdministrative: 'selling_general_administrative',
  researchDevelopment: 'research_development',
  operatingIncome: 'operating_income',
  ebitda: 'ebitda',
  ebit: 'ebit',
  interestExpense: 'interest_expense',
  pretaxIncome: 'pretax_income',
  incomeTax: 'income_tax',
  netIncome: 'net_income',
  eps: 'eps_basic',
  epsDiluted: 'eps_diluted',
  basicShares: 'basic_shares_outstanding',
  dilutedShares: 'diluted_shares_outstanding',
} as const;

export const BALANCE_METRICS = {
  cashAndEquivalents: 'cash_and_equivalents',
  shortTermInvestments: 'short_term_investments',
  accountsReceivable: 'accounts_receivable',
  inventory: 'inventory',
  otherCurrentAssets: 'other_current_assets',
  totalCurrentAssets: 'total_current_assets',
  propertyPlantEquipment: 'property_plant_equipment',
  goodwill: 'goodwill',
  intangibleAssets: 'intangible_assets',
  longTermInvestments: 'long_term_investments',
  otherNonCurrentAssets: 'other_non_current_assets',
  totalAssets: 'total_assets',

  accountsPayable: 'accounts_payable',
  shortTermDebt: 'short_term_debt',
  otherCurrentLiabilities: 'other_current_liabilities',
  totalCurrentLiabilities: 'total_current_liabilities',
  longTermDebt: 'long_term_debt',
  leaseLiabilities: 'lease_liabilities',
  otherNonCurrentLiabilities: 'other_non_current_liabilities',
  totalLiabilities: 'total_liabilities',

  commonStock: 'common_stock',
  additionalPaidInCapital: 'additional_paid_in_capital',
  retainedEarnings: 'retained_earnings',
  treasuryStock: 'treasury_stock',
  otherComprehensiveIncome: 'other_comprehensive_income',
  totalEquity: 'total_shareholders_equity',
  totalLiabilitiesAndEquity: 'total_liabilities_and_equity',
} as const;

export const CASH_FLOW_METRICS = {
  netIncome: 'net_income',
  depreciationAmortization: 'depreciation_amortization',
  stockBasedCompensation: 'stock_based_compensation',
  changeInWorkingCapital: 'change_in_working_capital',
  operatingCashFlow: 'cash_from_operating_activities',
  capitalExpenditure: 'capital_expenditure',
  investingCashFlow: 'cash_from_investing_activities',
  debtIssuanceRepayment: 'debt_issuance_repayment',
  shareIssuanceRepurchase: 'share_issuance_repurchase',
  dividendsPaid: 'dividends_paid',
  financingCashFlow: 'cash_from_financing_activities',
  netChangeInCash: 'net_change_in_cash',
  freeCashFlow: 'free_cash_flow',
} as const;

/** Ordered line specs the UI renders, per statement. Order IS the presentation
 *  contract — a P&L that lists net income above revenue is wrong even if every
 *  number is right — so it lives here beside the vocabulary rather than in a
 *  component. `total` marks subtotal rows the UI emphasises; `indent` nests. */
export interface StatementLineSpec {
  metric: string;
  label: string;
  total?: boolean;
  indent?: boolean;
  /** Section heading rendered above this line. */
  section?: string;
}

export const INCOME_STATEMENT_LINES: StatementLineSpec[] = [
  { metric: INCOME_METRICS.revenue, label: 'Revenue', total: true },
  { metric: INCOME_METRICS.costOfRevenue, label: 'Cost of revenue', indent: true },
  { metric: INCOME_METRICS.grossProfit, label: 'Gross profit', total: true },
  { metric: INCOME_METRICS.operatingExpenses, label: 'Operating expenses', indent: true },
  { metric: INCOME_METRICS.sellingGeneralAdministrative, label: 'Selling, general & administrative', indent: true },
  { metric: INCOME_METRICS.researchDevelopment, label: 'Research & development', indent: true },
  { metric: INCOME_METRICS.operatingIncome, label: 'Operating income', total: true },
  { metric: INCOME_METRICS.ebitda, label: 'EBITDA' },
  { metric: INCOME_METRICS.ebit, label: 'EBIT' },
  { metric: INCOME_METRICS.interestExpense, label: 'Interest expense', indent: true },
  { metric: INCOME_METRICS.pretaxIncome, label: 'Pre-tax income', total: true },
  { metric: INCOME_METRICS.incomeTax, label: 'Income tax', indent: true },
  { metric: INCOME_METRICS.netIncome, label: 'Net income', total: true },
  { metric: INCOME_METRICS.eps, label: 'EPS (basic)', section: 'Per share' },
  { metric: INCOME_METRICS.epsDiluted, label: 'EPS (diluted)' },
  { metric: INCOME_METRICS.basicShares, label: 'Shares outstanding (basic)' },
  { metric: INCOME_METRICS.dilutedShares, label: 'Shares outstanding (diluted)' },
];

export const BALANCE_SHEET_LINES: StatementLineSpec[] = [
  { metric: BALANCE_METRICS.cashAndEquivalents, label: 'Cash & cash equivalents', section: 'Assets' },
  { metric: BALANCE_METRICS.shortTermInvestments, label: 'Short-term investments', indent: true },
  { metric: BALANCE_METRICS.accountsReceivable, label: 'Accounts receivable', indent: true },
  { metric: BALANCE_METRICS.inventory, label: 'Inventory', indent: true },
  { metric: BALANCE_METRICS.otherCurrentAssets, label: 'Other current assets', indent: true },
  { metric: BALANCE_METRICS.totalCurrentAssets, label: 'Total current assets', total: true },
  { metric: BALANCE_METRICS.propertyPlantEquipment, label: 'Property, plant & equipment', indent: true },
  { metric: BALANCE_METRICS.goodwill, label: 'Goodwill', indent: true },
  { metric: BALANCE_METRICS.intangibleAssets, label: 'Intangible assets', indent: true },
  { metric: BALANCE_METRICS.longTermInvestments, label: 'Long-term investments', indent: true },
  { metric: BALANCE_METRICS.otherNonCurrentAssets, label: 'Other non-current assets', indent: true },
  { metric: BALANCE_METRICS.totalAssets, label: 'Total assets', total: true },

  { metric: BALANCE_METRICS.accountsPayable, label: 'Accounts payable', section: 'Liabilities' },
  { metric: BALANCE_METRICS.shortTermDebt, label: 'Short-term debt', indent: true },
  { metric: BALANCE_METRICS.otherCurrentLiabilities, label: 'Other current liabilities', indent: true },
  { metric: BALANCE_METRICS.totalCurrentLiabilities, label: 'Total current liabilities', total: true },
  { metric: BALANCE_METRICS.longTermDebt, label: 'Long-term debt', indent: true },
  { metric: BALANCE_METRICS.leaseLiabilities, label: 'Lease liabilities', indent: true },
  { metric: BALANCE_METRICS.otherNonCurrentLiabilities, label: 'Other non-current liabilities', indent: true },
  { metric: BALANCE_METRICS.totalLiabilities, label: 'Total liabilities', total: true },

  { metric: BALANCE_METRICS.commonStock, label: 'Common stock', section: 'Equity' },
  { metric: BALANCE_METRICS.additionalPaidInCapital, label: 'Additional paid-in capital', indent: true },
  { metric: BALANCE_METRICS.retainedEarnings, label: 'Retained earnings', indent: true },
  { metric: BALANCE_METRICS.treasuryStock, label: 'Treasury stock', indent: true },
  { metric: BALANCE_METRICS.otherComprehensiveIncome, label: 'Other comprehensive income', indent: true },
  { metric: BALANCE_METRICS.totalEquity, label: "Total shareholders' equity", total: true },
  { metric: BALANCE_METRICS.totalLiabilitiesAndEquity, label: 'Total liabilities + equity', total: true },
];

export const CASH_FLOW_LINES: StatementLineSpec[] = [
  { metric: CASH_FLOW_METRICS.netIncome, label: 'Net income', section: 'Operating' },
  { metric: CASH_FLOW_METRICS.depreciationAmortization, label: 'Depreciation & amortisation', indent: true },
  { metric: CASH_FLOW_METRICS.stockBasedCompensation, label: 'Stock-based compensation', indent: true },
  { metric: CASH_FLOW_METRICS.changeInWorkingCapital, label: 'Change in working capital', indent: true },
  { metric: CASH_FLOW_METRICS.operatingCashFlow, label: 'Cash from operating activities', total: true },

  { metric: CASH_FLOW_METRICS.capitalExpenditure, label: 'Capital expenditure', section: 'Investing', indent: true },
  { metric: CASH_FLOW_METRICS.investingCashFlow, label: 'Cash from investing activities', total: true },

  { metric: CASH_FLOW_METRICS.debtIssuanceRepayment, label: 'Debt issuance / repayment', section: 'Financing', indent: true },
  { metric: CASH_FLOW_METRICS.shareIssuanceRepurchase, label: 'Share issuance / repurchase', indent: true },
  { metric: CASH_FLOW_METRICS.dividendsPaid, label: 'Dividends paid', indent: true },
  { metric: CASH_FLOW_METRICS.financingCashFlow, label: 'Cash from financing activities', total: true },

  { metric: CASH_FLOW_METRICS.netChangeInCash, label: 'Net change in cash', section: 'Summary', total: true },
  { metric: CASH_FLOW_METRICS.freeCashFlow, label: 'Free cash flow', total: true },
];

export function linesFor(type: StatementType): StatementLineSpec[] {
  if (type === 'income') return INCOME_STATEMENT_LINES;
  if (type === 'balance') return BALANCE_SHEET_LINES;
  return CASH_FLOW_LINES;
}
